<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

        <title>WWF :: Registreren</title>
        <link href="/public/css/bootstrap.css" rel="stylesheet">
        <link href="/public/css/signin.css" rel="stylesheet">
    </head>

    <body>

        <div class="container">

            <form class="form-signin" role="form" method="post">
                <h2 class="form-signin-heading">Registreren</h2>
                <?php
                if (isset($error)):
                    echo sprintf("<div class=\"alert alert-danger\">%s</div>",
                                 $error);
                endif;
                ?>

                <input type="text" class="form-control" placeholder="Gebruikersnaam" name="username" required autofocus>
                <input type="password" class="form-control" placeholder="Wachtwoord" name="password" required>
                <input type="password" class="form-control" placeholder="Wachtwoord Herhalen" name="password2" required>
                <label class="checkbox">
                    <input type="checkbox" value="tos" name="tos"> Ik ga akkoord met de niet bestaande voorwaarden.
                </label>
                <button class="btn btn-lg btn-primary btn-block" type="submit" name="submit">Registeren</button>
            </form>

        </div> <!-- /container -->
    </body>
</html>
