<?php

use WorthyStonyMorning\Helpers\FormHelper as Form;

include VIEW_PATH . "partials/adminHeader.phtml";
?>

<form role="form" method="post" enctype="multipart/form-data">

    <?php if (isset($errors)): ?>
        <div class="alert alert-danger">
            <?php
            foreach ($errors as $error):
                printf("<p>%s</p>", $error);
            endforeach;
            ?>
        </div>
    <?php endif; ?>

    <div class="form-group">
        <label for="image">Bestand</label>
        <input name="image" type="file" class="form-control"
               id="image" required="required"  <?php Form::val($data, "image"); ?>>
    </div>
    <button name="submit" type="submit" class="btn btn-default">Uploaden</button>
</form>
<?php
include VIEW_PATH . "partials/footer.phtml";
