<?php

use WorthyStonyMorning\Helpers\FormHelper as Form;

include VIEW_PATH . "partials/header.phtml";
?>
<div class="row">
    <div class="col-lg-12">

        <?php if (isset($content)): ?>
            <div class="row">
                <div class="col-lg-12">
                    <?php echo $content; ?>
                </div>
            </div>
            <hr />
        <?php endif; ?>


        <form role="form" method="post">


            <?php if (isset($errors)): ?>
                <div class="alert alert-danger">
                    <?php
                    foreach ($errors as $error):
                        printf("<p>%s</p>", $error);
                    endforeach;
                    ?>
                </div>
            <?php endif; ?>

            <div class="form-group">
                <label for="contact_email">Uw email adres</label>
                <input name="contact_email" type="email" class="form-control"
                       id="contact_email" placeholder="Email adres" required="required"
                       <?php
                       Form::val($data, "contact_email");
                       ?>>
            </div>
            <div class="form-group">
                <label for="contact_name">Uw naam</label>
                <input name="contact_name" type="text" class="form-control"
                       id="contact_name" required="required"
                       <?php Form::val($data,
                                                               "contact_name"); ?>>
            </div>

            <div class="form-group">
                <label for="contact_message">Uw bericht</label>
                <textarea name="contact_message" id="contact_message" class="form-control"
                          rows="3" required="required"><?php echo (isset($data['contact_message'])) ? $data['contact_message'] : ""; ?></textarea>
            </div>

            <button name="submit" type="submit" class="btn btn-default">Verzenden</button>
        </form>
        <?php
        include VIEW_PATH . "partials/footer.phtml";
