<div class="row">
    <div class="col-lg-12">
        <div class="thumbnail">
            <img class="img-responsive" src="http://placehold.it/800x300" alt="">
            <div class="caption-full">
                <h4 class="pull-right">&euro;2,99</h4>
                <h4><a href="#">Eierkoeken & Vifit</a>
                </h4>
                <p>Heerlijk lekkere eirekoken en een pakje Vifit yogurt drink.</p>
            </div>
            <a class="btn btn-primary">Kopen!</a>
        </div>
    </div>
</div>