<?php

use Aggressiveswallow\Helpers\LoginHelper as Login;
?>
<!DOCTYPE html>
<html lang = "en">

    <head>
        <meta charset = "utf-8">
        <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
        <meta name = "description" content = "Web2 webshop webmakelaar">
        <meta name = "author" content = "Yorick & Patrick">

        <title>WWF
            <?php
            if (isset($pageTitle)):
                echo sprintf(" :: %s", $pageTitle);
            endif;
            ?>
        </title>

        <link href="<?php echo BASE_URL; ?>public/css/bootstrap.css" rel="stylesheet">
        <link href="<?php echo BASE_URL; ?>public/css/custom.css" rel="stylesheet">
        <link href="<?php echo BASE_URL; ?>public/css/jasny-bootstrap.min.css" rel="stylesheet" media="screen">
    </head>

    <body>

        <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">WWF</a>
                </div>

                <div class="collapse navbar-collapse">

                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="<?php echo BASE_URL; ?>admin/index">Dashboard</a></li>
                    </ul>


                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <?php
                            $user = Login::getLoggedInUser();
                            ?>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $user->getName(); ?> <b class="caret"></b></a>

                            <ul class="dropdown-menu">

                                <li><a href="<?php echo BASE_URL; ?>account/logout">Uitloggen</a></li>
                                <li><a href="<?php echo BASE_URL; ?>admin/index">Beheren</a></li>

                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /.container -->
        </nav>

        <div class="container">
            <?php
            include "nav/breadcrums.phtml";
