<div class="row">
    <div class="col-md-11">
        <h3><?php echo $event->getTitle(); ?></h3>
        <p><?php echo $event->getShortdesc(); ?></p>
    </div>
    <div class="col-md-1 text-right">
        <small>
            <a href = "<?php echo BASE_URL; ?>event\edit\eventId=<?php echo $event->getId(); ?>">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            <a href="<?php echo BASE_URL; ?>event\delete\eventId=<?php echo $event->getId(); ?>">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
        </small>
    </div>
</div>