<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Web2 webshop webmakelaar">
        <meta name="author" content="Yorick & Patrick">

        <title>WWF
            <?php
            if (isset($pageTitle)):
                echo sprintf(" :: %s", $pageTitle);
            endif;
            ?>
        </title>

        <link href="<?php echo BASE_URL; ?>public/css/bootstrap.css" rel="stylesheet">
        <link href="<?php echo BASE_URL; ?>public/css/custom.css" rel="stylesheet">
        <link href="<?php echo BASE_URL; ?>public/css/jasny-bootstrap.min.css" rel="stylesheet" media="screen">
    </head>

    <body>

        <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">WWF</a>
                </div>


                <?php
                include "nav/menu.phtml";
                ?>
            </div>
            <!-- /.container -->
        </nav>

        <div class="container">
