<?php
include VIEW_PATH . "partials/header.phtml";
?>
<div class="row">
    <div class="page-header">
        <h1><?php echo $title; ?> <small><?php echo $shortMessage; ?></small></h1>
    </div>
</div>
<div class="row">
    <div class="alert alert-<?php echo $class; ?> fade in">
        <h4>
            <?php
            echo $title . " ";
            echo $shortMessage;
            ?>
        </h4>
        <p><?php echo $description; ?></p>
        <p>
            <a href="/" class="btn btn-<?php echo $class; ?>">Naar de homepagina</a>
        </p>
    </div>
</div>
<?php
include VIEW_PATH . "partials/footer.phtml";
