<?php

use WorthyStonyMorning\Helpers\FormHelper as Form;

include VIEW_PATH . "partials/adminHeader.phtml";
?>
<form role="form" method="post">


    <?php if (isset($errors)): ?>
        <div class="alert alert-danger">
            <?php
            foreach ($errors as $error):
                printf("<p>%s</p>", $error);
            endforeach;
            ?>
        </div>
    <?php endif; ?>

    <input name="event_id" type="hidden" <?php Form::val($data, "event_id"); ?>>
    <div class="form-group">
        <label for="event_email">Contact persoon</label>
        <input name="event_email" type="email" class="form-control"
               id="event_email" placeholder="Email adres" required="required"
               <?php Form::val($data, "event_email"); ?>>
    </div>
    <div class="form-group">
        <label for="event_title">Titel</label>
        <input name="event_title" type="text" class="form-control"
               id="event_title" required="required"
               <?php Form::val($data, "event_title"); ?>>
    </div>

    <div class="form-group">
        <label for="event_time">Tijdstip</label>
        <input name="event_time" type="datetime-local" class="form-control"
               id="event_time" required="required"
               <?php Form::val($data, "event_time"); ?>>
    </div>

    <div class="form-group">
        <label for="event_shortdesc">Korte omschrijving</label>
        <input name="event_shortdesc" type="text" class="form-control"
               id="event_shortdesc" required="required"
               <?php Form::val($data, "event_shortdesc"); ?>>
    </div>

    <div class="form-group">
        <label for="event_longdesc">Lange omschrijving</label>
        <textarea name="event_longdesc" id="event_longdesc" class="form-control"
                  rows="3" required="required"><?php echo (isset($data['event_longdesc'])) ? $data['event_longdesc'] : ""; ?></textarea>
    </div>

    <button name="submit" type="submit" class="btn btn-default">Opslaan</button>
</form>
<?php
include VIEW_PATH . "partials/footer.phtml";
