<?php
include VIEW_PATH . "partials/header.phtml";
?>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img alt="First slide" src="http://placehold.it/1140x400">
            <div class="carousel-caption">
                <h3>First slide</h3>
                <p>Some info</p>
            </div>
        </div>
        <div class="item">
            <img alt="Second Image" src="http://placehold.it/1140x400">
            <div class="carousel-caption">
                <h3>Second slide</h3>
                <p>Some info</p>
            </div>
        </div>
        <div class="item">
            <img alt="Third slide" src="http://placehold.it/1140x400">
            <div class="carousel-caption">
                <h3>Third slide</h3>
                <p>Some info</p>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

<div class="row">
    <div class="col-lg-12">

        <?php
        if (isset($content)):
            echo $content;
        endif;
        ?>
    </div>
</div>
<!-- /.row -->

<?php
$bottomJs[] = file_get_contents(VIEW_PATH . "common/ajaxReload.js");
include VIEW_PATH . "partials/footer.phtml";
