<?php
include VIEW_PATH . "partials/header.phtml";
?>


<?php if (isset($content)): ?>
    <div class="row">
        <div class="col-lg-8">
            <?php echo $content; ?>
        </div>
        <div class="col-lg-4">
            <?php if (isset($images) && count($images) > 0): ?>
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <?php
                        $firstIndicator = true;
                        $i              = 0;
                        foreach ($images as $image):
                            ?>
                            <li
                                data-target="#carousel-example-generic"
                                data-slide-to="<?php echo $i; ?>"
                                <?php
                                echo ($firstIndicator) ? "class=\"active\"" : "";
                                $i++;
                                $firstIndicator = false;
                                ?>
                                >
                            </li>

                        <?php endforeach; ?>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <?php
                        $first = true;
                        foreach ($images as $image):
                            ?>
                            <div class="item <?php echo ($first) ? "active" : ""; ?>">
                                <img alt="Slide" src="<?php echo BASE_URL . "public/uploads/" . $image->getPath(); ?> ">
                            </div>
                            <?php $first = false; ?>
                        <?php endforeach; ?>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<!-- /.row -->

<?php
$bottomJs[] = file_get_contents(VIEW_PATH . "common/ajaxReload.js");
include VIEW_PATH . "partials/footer.phtml";
