<?php

use Aggressiveswallow\Helpers\LoginHelper as Login;
?>
<div class="collapse navbar-collapse">

    <ul class="nav navbar-nav navbar-left">
        <li><a href="<?php echo BASE_URL; ?>event/list">Evenementen</a></li>
        <li><a href="<?php echo BASE_URL; ?>contact/index">Contact</a></li>
    </ul>


    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <?php
            $user = Login::getLoggedInUser();
            $text = (Login::isLoggedIn()) ? $user->getName() : "Niet ingelogd";
            ?>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $text; ?> <b class="caret"></b></a>

            <ul class="dropdown-menu">
                <?php if (!Login::isLoggedIn()): ?>
                    <li><a href="<?php echo BASE_URL; ?>account/login">Inloggen</a></li>
                    <li><a href="<?php echo BASE_URL; ?>account/register">Registreren</a></li>
                <?php else: ?>
                    <li><a href="<?php echo BASE_URL; ?>account/logout">Uitloggen</a></li>
                    <li><a href="<?php echo BASE_URL; ?>admin/index">Beheren</a></li>
                <?php endif; ?>
            </ul>
        </li>
    </ul>
</div>
<!-- /.navbar-collapse -->