<?php

use Aggressiveswallow\Tools\Container;
use Aggressiveswallow\Helpers\Cart;
use Aggressiveswallow\Helpers\LoginHelper as Login;

function generateMenu() {

    $nav = Aggressiveswallow\Tools\Container::make("navigation");
    foreach ($nav as $navItem):
        generateLink($navItem);
    endforeach;
}

function generateLink($navItem) {
    $regularLink = "<li><a href=\"%s\">%s</a></li>";
    $menuLink = "<a href=\"%s\" data-toggle=\"dropdown\">%s <b class=\"caret\"></b></a>";
    /* @var $navItem \Aggressiveswallow\Helpers\NavItem */
    if ($navItem->hasChildren()) {
        echo "<li class='dropdown'>";
        echo sprintf($menuLink, $navItem->getUri(), $navItem->getName());
        echo "<ul class='dropdown-menu'>";
        foreach ($navItem->getChildren() as $childItem):
            generateChild($childItem);
        endforeach;
    echo "</ul>";
    echo "</li>";
    }else {
        echo sprintf($regularLink, $navItem->getUri(), $navItem->getName());
    }
}

function generateChild($navItem) {
    $link = "<a href=\"%s\">%s</a>";
    $regularLink = "<li><a href=\"%s\">%s</a></li>";
    /* @var $navItem \Aggressiveswallow\Helpers\NavItem */
    if ($navItem->hasChildren()) {
        echo "<li class='dropdown-submenu'>";
        echo sprintf($link, $navItem->getUri(), $navItem->getName());
        echo "<ul class='dropdown-menu'>";
        foreach ($navItem->getChildren() as $childItem):
            generateChild($childItem);
        endforeach;
    echo "</ul>";
    echo "</li>";
    }else {
        echo sprintf($regularLink, $navItem->getUri(), $navItem->getName());
    }
}
?>


<div class = "collapse navbar-collapse">
    <ul class = "nav navbar-nav">

        <?php
        generateMenu();
        ?>

    </ul>
    
    <?php
    chdir(BASE_PATH);
    $sess = Container::make("session");
    $cartText = "Leeg";
    $cart_name = Cart::SESSION_NAME;
    if ($sess->has($cart_name)):
        $count = $sess->$cart_name->itemCount();
        if ($count > 0):
            $cartText = sprintf(($count == 1 ? " %s item" : "%s items"), $count);

        endif;
    endif;
    ?>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="/cart/show/"><span class="glyphicon glyphicon-shopping-cart"></span><?php echo $cartText; ?></a></li>
        <li class="dropdown">
            <?php
            $user = Login::getLoggedInUser();
            $text = (Login::isLoggedIn()) ? $user->getName() : "Niet ingelogd";
            ?>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $text; ?> <b class="caret"></b></a>

            <ul class="dropdown-menu">
                <?php if (!Login::isLoggedIn()): ?>
                    <li><a href="/account/login">Inloggen</a></li>
                    <li><a href="/account/register">Registreren</a></li>
                <?php else: ?>
                    <li><a href="/account/logout">Uitloggen</a></li>
                <?php endif; ?>
            </ul>
        </li>
    </ul>
</div>
<!-- /.navbar-collapse -->